dist: trusty
sudo: required
language: android
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
addons:
  apt:
    sources:
      - sourceline: deb https://dl.yarnpkg.com/debian/ stable main
        key_url: https://dl.yarnpkg.com/debian/pubkey.gpg
      - sourceline: deb http://dl.google.com/linux/chrome/deb/ stable main
        key_url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default
      - yarn
      - jq
      - gradle
      - google-chrome-stable
licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.npm
before_install:
  - nvm install 8
  - npm i -g cordova ionic
before_script:
  - mkdir www
  - cp src/assets/data/secret.ts.template src/assets/data/secret.ts
script:
  - npm install
  - npm run lint
  - npm run lint:css
  - cordova prepare
  - npm run build
  - cordova plugin add cordova-plugin-whitelist
  - cordova plugin ls
  - cordova platform ls
  - ionic cordova platform remove android
  - ionic cordova platform add android@6.4.0
  - ionic cordova build android
env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
