dist: trusty
sudo: required
language: node_js
node_js:
  - node

install:
  - npm i -g cordova ionic
  - npm i

before_script:
  - mkdir www
  - cp src/assets/data/secret.ts.template src/assets/data/secret.ts

script:
  - npm run lint
  - npm run lint:css
  - cordova prepare
  - npm run build
